In [1]:
import time
import pandas as pd

def calculate_metrics(y_test,Y_predicted):

    from sklearn import metrics
    from sklearn.metrics import classification_report,confusion_matrix

    accuracy = metrics.accuracy_score(y_test,Y_predicted)
    print("accuracy = "+str(round(accuracy * 100,2))+"%")

    confusion_mat = confusion_matrix(y_test,Y_predicted)

    print(confusion_mat)
    print(confusion_mat.shape)

    print("TP\tFP\tFN\tTN\tSensitivity\tSpecificity")
    for i in range(confusion_mat.shape[0]):
        # i means which class to choose to do one-vs-the-rest calculation
        # rows are actual obs whereas columns are predictions
        TP = round(float(confusion_mat[i,i]),2)  # correctly labeled as i
        FP = round(float(confusion_mat[:,i].sum()),2) - TP  # incorrectly labeled as i
        FN = round(float(confusion_mat[i,:].sum()),2) - TP  # incorrectly labeled as non-i
        TN = round(float(confusion_mat.sum().sum()),2) - TP - FP - FN
        print(str(TP)+"\t"+str(FP)+"\t"+str(FN)+"\t"+str(TN))
        sensitivity = round(TP / (TP + FN),2)
        specificity = round(TN / (TN + FP),2)
        print("\t"+str(sensitivity)+"\t\t"+str(specificity)+"\t\t")


    f_score = metrics.f1_score(y_test,Y_predicted)
    print("f_score = ",f_score)
    




In [2]:
def neural_network(dataset,class_labels,test_size):

    import numpy as np
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.neural_network import MLPClassifier

    X = pd.read_csv(dataset)
    Y = pd.read_csv(class_labels)
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size= test_size, random_state=42) 

    model = MLPClassifier(hidden_layer_sizes=(100), activation='logistic',random_state = 42)
    model.fit(X_train,y_train)
    Y_predicted = model.predict(X_test)

    return y_test,Y_predicted

In [3]:
def random_forests(dataset,class_labels,test_size):

    import numpy as np
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.ensemble import RandomForestClassifier
    from sklearn import metrics
    X = pd.read_csv(dataset)
    Y = pd.read_csv(class_labels)
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size= test_size, random_state=42)   
    model = RandomForestClassifier(n_estimators = 5, criterion = 'entropy',random_state = 42)
    model.fit(X_train,y_train)
    Y_predicted = model.predict(X_test)
    print('w = ',model.feature_importances_)
    return y_test,Y_predicted



In [4]:
def support_vector_machines(dataset,class_labels,test_size):

    import numpy as np
    from sklearn import svm
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LassoCV
    X = pd.read_csv(dataset)
    Y = pd.read_csv(class_labels)
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size= test_size, random_state=42)  
    # 'rbf' value is the gaussian kernel, 'C' is the coefficient used for regularization during training
    model = svm.SVC(kernel='rbf',C=2)
    model.fit(X_train,y_train)
    Y_predicted = model.predict(X_test)
    #print('w = ',model.coef_)
    
    return y_test,Y_predicted



In [5]:
def main():

    dataset = "Dataset.csv"
    class_labels = "Target_Labels.csv"
    test_size = 0.3
    print("\nrunning neural networks...")
    start_time = time.time()
    y_test,Y_predicted = neural_network(dataset,class_labels,test_size)
    calculate_metrics(y_test,Y_predicted)
    end_time = time.time()
    print("runtime = "+str(end_time - start_time)+" seconds")

    print("\nrunning random forests...")
    start_time = time.time()
    y_test,Y_predicted = random_forests(dataset,class_labels,test_size)
    calculate_metrics(y_test,Y_predicted)
    end_time = time.time()
    print("runtime = "+str(end_time - start_time)+" seconds")

    print("\nrunning support vector machines...")
    start_time = time.time()
    y_test,Y_predicted = support_vector_machines(dataset,class_labels,test_size)
    calculate_metrics(y_test,Y_predicted)
    end_time = time.time()
    print("runtime = "+str(end_time - start_time)+" seconds")
    
if __name__ == '__main__':
    start_time = time.time()
    main()
    end_time = time.time()
    print("runtime = "+str(end_time - start_time)+" seconds")


running neural networks...


C:\Users\shrut\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\shrut\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


accuracy = 89.03%
[[1246  209]
 [ 155 1707]]
(2, 2)
TP	FP	FN	TN	Sensitivity	Specificity
1246.0	155.0	209.0	1707.0
	0.86		0.92		
1707.0	209.0	155.0	1246.0
	0.92		0.86		
f_score =  0.9036527263102171
runtime = 11.949618577957153 seconds

running random forests...


C:\Users\shrut\AppData\Local\Temp/ipykernel_4280/3890057621.py:12: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train,y_train)
C:\Users\shrut\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


w =  [0.01936439 0.02117938 0.01876878 0.01120847 0.01026978 0.07436608
 0.0954229  0.01459551 0.01338997 0.0360258  0.53999957 0.07674631
 0.03680964 0.01144118 0.01225402 0.00815821]
accuracy = 89.63%
[[1293  162]
 [ 182 1680]]
(2, 2)
TP	FP	FN	TN	Sensitivity	Specificity
1293.0	182.0	162.0	1680.0
	0.89		0.9		
1680.0	162.0	182.0	1293.0
	0.9		0.89		
f_score =  0.9071274298056156
runtime = 0.32981419563293457 seconds

running support vector machines...
accuracy = 90.05%
[[1254  201]
 [ 129 1733]]
(2, 2)
TP	FP	FN	TN	Sensitivity	Specificity
1254.0	129.0	201.0	1733.0
	0.86		0.93		
1733.0	201.0	129.0	1254.0
	0.93		0.86		
f_score =  0.9130663856691253
runtime = 3.3211159706115723 seconds
runtime = 15.601557493209839 seconds
